src/blog/urls.py
from django.urls import path
from blog.views import(

	create_blog_view,
	detail_blog_view,
	edit_blog_view,
	create_comment_view,
	comment_view,
	create_doctor_blog_view,
	doctor_detail_blog_view,
	doctor_edit_blog_view,

)

app_name = 'blog'

urlpatterns = [
	path('create/', create_blog_view, name="create"),
	path('createblog/', create_doctor_blog_view, name="doctorblogcreate"),
	path('<slug>/', detail_blog_view, name='detail'),
	path('<slug>/detail', doctor_detail_blog_view, name='doctorblogdetail'),
	path('<slug>/', create_comment_view, name='comment'),
	path('<slug>/', comment_view, name='comments'),
	path('<slug>/edit', edit_blog_view, name='edit'),
	path('<slug>/editblog', doctor_edit_blog_view, name='doctorblogedit'),


]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from personal.views import(
	home_screen_view,
    index_view,
    blogpost_view,
    userprofile_view,
    doctor_index_view,
    doctor_blogpost_view,
    doc_profile_view,
    covid_view,
    product_view,
       
)
from account.views import(
    registration_view,
    logout_view,
    login_view,
    doc_login_view,
    doc_reg_view,

)
urlpatterns = [
    path('',home_screen_view, name="home"),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', 'blog')),
    path('blogpost/',blogpost_view, name="blogpost"),
    path('doctor_blogpost/',doctor_blogpost_view, name="doctor_blogpost"),
    path('index/',index_view, name="index"),
    path('logout/',logout_view, name="logout"),
    path('login/',login_view, name="login"),
    path('doctor_login/',doc_login_view, name="doctor_login"),
    path('doctor_index/',doctor_index_view, name="doctor_index"),
    path('register/',registration_view, name="register"),
    path('doctor_register/',doc_reg_view, name="doctorregister"),
    path('userprofile/',userprofile_view, name="userprofile"),
    path('doctor_profile/',doc_profile_view, name="doctorprofile"),
    path('covidlist/',covid_view, name="covidlist"),
    path('product/',product_view, name="product"),
    path('', include('store.urls', 'store'))

   
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/personal/models.py
from django.db import models

# Create your models here.

src/personal/views.py
from django.shortcuts import render
from operator import attrgetter
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

from blog.views import get_blog_queryset
from blog.models import BlogPost

BLOG_POSTS_PER_PAGE = 5

def home_screen_view(request):
	print(request.headers)
	return render(request, "base.html", {})

def index_view(request):
	print(request.headers)
	return render(request, "index.html", {})

def userprofile_view(request):
	print(request.headers)
	return render(request, "userprofile.html", {})	

def blogpost_view(request):
	
	context = {}

	# Search
	query = ""
	if request.GET:
		query = request.GET.get('q', '')
		context['query'] = str(query)

	blog_posts = sorted(get_blog_queryset(query), key=attrgetter('date_updated'), reverse=True)



	# Pagination
	page = request.GET.get('page', 1)
	blog_posts_paginator = Paginator(blog_posts, BLOG_POSTS_PER_PAGE)
	try:
		blog_posts = blog_posts_paginator.page(page)
	except PageNotAnInteger:
		blog_posts = blog_posts_paginator.page(BLOG_POSTS_PER_PAGE)
	except EmptyPage:
		blog_posts = blog_posts_paginator.page(blog_posts_paginator.num_pages)

	context['blog_posts'] = blog_posts

	return render(request, "personal/bpost.html", context)	

def doctor_index_view(request):
	print(request.headers)
	return render(request, "doctor_index.html", {})	

def doctor_blogpost_view(request):
	
	context = {}

	# Search
	query = ""
	if request.GET:
		query = request.GET.get('q', '')
		context['query'] = str(query)

	blog_posts = sorted(get_blog_queryset(query), key=attrgetter('date_updated'), reverse=True)



	# Pagination
	page = request.GET.get('page', 1)
	blog_posts_paginator = Paginator(blog_posts, BLOG_POSTS_PER_PAGE)
	try:
		blog_posts = blog_posts_paginator.page(page)
	except PageNotAnInteger:
		blog_posts = blog_posts_paginator.page(BLOG_POSTS_PER_PAGE)
	except EmptyPage:
		blog_posts = blog_posts_paginator.page(blog_posts_paginator.num_pages)

	context['blog_posts'] = blog_posts

	return render(request, "personal/docbpost.html", context)	

def doc_profile_view(request):
	print(request.headers)
	return render(request, "doctorprofile.html", {})	

def covid_view(request):
	print(request.headers)
	return render(request, "covid.html", {})

def product_view(request):
	print(request.headers)
	return render(request, "product.html", {})	

src/personal/templates/personal/bpost.html
{% extends 'blogpost.html' %}

{% load static %}

{% block content %}
<style>

	@media (max-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}

	@media (min-width: 768px) { 
		.right-column{
			margin-left: 20px;
		}
	}

	.blog-post-container{
		margin-bottom: 20px;
		width: 100%;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}

	.left-column{
		padding:0px;
	}

	.right-column{
		padding:0px;
	}
	.lead{
		font-size: 17px;
		text-align: left;
	}
	
</style>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">


<!-- main content -->
<div class="container">
	<div class="row">

		<!-- blog feed -->
		<div class="left-column col-lg-7 offset-lg-1">

			<!-- Top 'create post' bar -->
			<div class="d-lg-none mb-3">
				<div class="card m-auto d-flex flex-column p-3">
					
					<p class="lead">Create Your Blog Here!!&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;You Can Post New Blog.&emsp;&emsp;&emsp;&emsp;</p>
					<p class="m-auto"><a class="btn btn-primary" href="{% url 'blog:create' %}">Create post</a></p>
				</div>
			</div>
			<!-- end Top 'create post' bar -->

			<!-- Blog posts-->
			{% if blog_posts %}
				{% for post in blog_posts %}
					<div class="blog-post-container">
						{% include 'blog/snippets/blog_post_snippet.html' with blog_post=post %}
					</div>
				{% endfor %}
			{% else %}
				<div class="blog-post-container">
						{% include 'blog/snippets/blog_post_snippet.html' with query=query %}
				</div>
			{% endif %}
			<!-- End Blog posts-->

		<!-- Pagination -->
		{% include 'blog/snippets/blog_post_pagination.html' with blog_posts=blog_posts %}

		</div>
		<!-- end blog feed -->


		<!-- Right 'create post' column  -->
		<div class="right-column col-lg-3 d-lg-flex d-none flex-column">

			<div class="card create-post-bar d-flex flex-column p-3">
				
				<p class="lead">Create Your Blog Here!!&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;You Can Post New Blog.&emsp;&emsp;&emsp;&emsp;</p>
				<p class="m-auto"><a class="btn btn-primary" href="{% url 'blog:create' %}">Create post</a></p>
			</div>
		
		</div>
		<!-- end Right 'create post' column  -->



	</div>
</div>



{% endblock content %}

src/personal/templates/personal/docbpost.html
{% extends 'doctor_blogpost.html' %}

{% load static %}

{% block content %}
<style>

	@media (max-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}

	@media (min-width: 768px) { 
		.right-column{
			margin-left: 20px;
		}
	}

	.blog-post-container{
		margin-bottom: 20px;
		width: 100%;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}

	.left-column{
		padding:0px;
	}

	.right-column{
		padding:0px;
	}
	.lead{
		font-size: 17px;
		text-align: left;
	}
	
</style>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">


<!-- main content -->
<div class="container">
	<div class="row">

		<!-- blog feed -->
		<div class="left-column col-lg-7 offset-lg-1">

			<!-- Top 'create post' bar -->
			<div class="d-lg-none mb-3">
				<div class="card m-auto d-flex flex-column p-3">
					
					<p class="lead">Create Your Blog Here!!&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;You Can Post New Blog.&emsp;&emsp;&emsp;&emsp;</p>
					<p class="m-auto"><a class="btn btn-primary" href="{% url 'blog:doctorblogcreate' %}">Create post</a></p>
				</div>
			</div>
			<!-- end Top 'create post' bar -->

			<!-- Blog posts-->
			{% if blog_posts %}
				{% for post in blog_posts %}
					<div class="blog-post-container">
						{% include 'blog/snippets/doctor_blog_post_snippet.html' with blog_post=post %}
					</div>
				{% endfor %}
			{% else %}
				<div class="blog-post-container">
						{% include 'blog/snippets/doctor_blog_post_snippet.html' with query=query %}
				</div>
			{% endif %}
			<!-- End Blog posts-->

		<!-- Pagination -->
		{% include 'blog/snippets/doctor_blog_post_pagination.html' with blog_posts=blog_posts %}

		</div>
		<!-- end blog feed -->


		<!-- Right 'create post' column  -->
		<div class="right-column col-lg-3 d-lg-flex d-none flex-column">

			<div class="card create-post-bar d-flex flex-column p-3">
				
				<p class="lead">Create Your Blog Here!!&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;You Can Post New Blog.&emsp;&emsp;&emsp;&emsp;</p>
				<p class="m-auto"><a class="btn btn-primary" href="{% url 'blog:doctorblogcreate' %}">Create post</a></p>
			</div>
		
		</div>
		<!-- end Right 'create post' column  -->



	</div>
</div>



{% endblock content %}