src/blog/urls.py
from django.urls import path
from blog.views import(

	create_blog_view,
	detail_blog_view,
	edit_blog_view,
	create_comment_view,
	comment_view,
	create_doctor_blog_view,
	doctor_detail_blog_view,
	doctor_edit_blog_view,

)

app_name = 'blog'

urlpatterns = [
	path('create/', create_blog_view, name="create"),
	path('createblog/', create_doctor_blog_view, name="doctorblogcreate"),
	path('<slug>/', detail_blog_view, name='detail'),
	path('<slug>/detail', doctor_detail_blog_view, name='doctorblogdetail'),
	path('<slug>/', create_comment_view, name='comment'),
	path('<slug>/', comment_view, name='comments'),
	path('<slug>/edit', edit_blog_view, name='edit'),
	path('<slug>/editblog', doctor_edit_blog_view, name='doctorblogedit'),


]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from personal.views import(
	home_screen_view,
    index_view,
    blogpost_view,
    userprofile_view,
    doctor_index_view,
    doctor_blogpost_view,
    doc_profile_view,
    covid_view,
    product_view,
       
)
from account.views import(
    registration_view,
    logout_view,
    login_view,
    doc_login_view,
    doc_reg_view,

)
urlpatterns = [
    path('',home_screen_view, name="home"),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', 'blog')),
    path('blogpost/',blogpost_view, name="blogpost"),
    path('doctor_blogpost/',doctor_blogpost_view, name="doctor_blogpost"),
    path('index/',index_view, name="index"),
    path('logout/',logout_view, name="logout"),
    path('login/',login_view, name="login"),
    path('doctor_login/',doc_login_view, name="doctor_login"),
    path('doctor_index/',doctor_index_view, name="doctor_index"),
    path('register/',registration_view, name="register"),
    path('doctor_register/',doc_reg_view, name="doctorregister"),
    path('userprofile/',userprofile_view, name="userprofile"),
    path('doctor_profile/',doc_profile_view, name="doctorprofile"),
    path('covidlist/',covid_view, name="covidlist"),
    path('product/',product_view, name="product"),
    path('', include('store.urls', 'store'))

   
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/store/urls.py
from django.urls import path

from store.views import(

	store,
	cart,
	checkout,
	updateItem,
	processOrder,

)

app_name = 'store'

urlpatterns = [
	#Leave as empty string for base url
	path('store/', store, name="store"),
	path('cart/', cart, name="cart"),
	path('checkout/', checkout, name="checkout"),
	path('update_item/', updateItem, name="update_item"),
	path('process_order/', processOrder, name="process_order"),

]

src/store/models.py
from django.db import models

from django.conf import settings




# Create your models here.

class Customer(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='customer')
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)


def __str__(self):
    return self.name


class Product(models.Model):
    name = models.CharField(max_length=200, null=True)
    price = models.FloatField()
    digital = models.BooleanField(default=False, null=True, blank=False)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except Exception:
            url = ''
        return url


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)

    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping
    


    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True, )
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)

    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)

    address = models.CharField(max_length=200, null=True)

    city = models.CharField(max_length=200, null=True)

    state = models.CharField(max_length=280, null=True)

    zipcode = models.CharField(max_length=200, null=True)

    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

src/store/views.py
from django.shortcuts import render
from django.core.exceptions import ObjectDoesNotExist
from django.http import JsonResponse
import json
import datetime


from .models import *

# Create your views here.

def store(request):

    if request.user.is_authenticated:
        try:
            request.user.customer
        except ObjectDoesNotExist:
            Customer.objects.create(name=request.user.fullname, email=request.user.email)

        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_total':0, 'get_cart_items':0, 'shipping':False}
        cartItems = order['get_cart_items'] 

    products = Product.objects.all()
    context = {'products':products, 'cartItems':cartItems}
    return render(request, 'store/store.html', context)

def cart(request):

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_total':0, 'get_cart_items':0, 'shipping':False}
        cartItems = order['get_cart_items'] 
        
    context = {'items':items, 'order':order, 'cartItems':cartItems}
    return render(request, 'store/cart.html', context)


def checkout(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_total':0, 'get_cart_items':0, 'shipping':False}
        cartItems = order['get_cart_items'] 
        
    context = {'items':items, 'order':order, 'cartItems':cartItems}
    return render(request, 'store/checkout.html', context)


def updateItem(request):
    data= json.loads(request.body)
    productId = data['productId']
    action = data['action']
    print('Action:', action)
    print('productId:', productId)


    customer = request.user.customer
    product  = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)

    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse('Item was added', safe=False)


def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    print(data)

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        total = float(data['form']['total'])
        order.transaction_id = transaction_id

        if total == order.get_cart_total:
            order.complete = True
        order.save()

        print(order.shipping)

        if order.shipping:
           ShippingAddress.objects.create(
                   customer=customer,
                   order=order,
                   address=data['shipping']['address'],
                   city=data['shipping']['city'],
                   state=data['shipping']['state'],
                   zipcode=data['shipping']['zipcode'],

            )    

    else:
        print('User is not logged in...')
    return JsonResponse('Payemnt complete!', safe=False)
      

src/store/templates/store/cart.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

<div class="row">
        <div class="col-lg-12">
            <div class="box-element">

             <a  class="btn btn-outline-dark" href="{% url 'store:store' %}">&#x2190; Continue Shopping</a>

                <br>
                <br>
                
                <table class="table">
                    <tr>
                        <th><h5>Items: <strong>{{order.get_cart_items}}</strong></h5></th>
                        <th><h5>Total:<strong>৳{{order.get_cart_total|floatformat:2}}</strong></h5></th>
                        <th>
                            <a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'store:checkout' %}">Checkout</a>
                        </th>
                    </tr>
                </table>
                

            </div>

            <br>
            <div class="box-element">
                <div class="cart-row">
                    <div style="flex:2"></div>
                    <div style="flex:2"><strong>Item</strong></div>
                    <div style="flex:1"><strong>Price</strong></div>
                    <div style="flex:1"><strong>Quantity</strong></div>
                    <div style="flex:1"><strong>Total</strong></div>
                </div>
                
                {% for item in items %}

                <div class="cart-row">
                    <div style="flex:2"><img class="row-image" src="{{item.product.image.url}}"></div>
                    <div style="flex:2"><p>{{item.product.name}}</p></div>
                    <div style="flex:1"><p>{{item.product.price|floatformat:2}}</p></div>
                    <div style="flex:1">
                        <p class="quantity">{{item.quantity}}</p>
                        <div class="quantity">
                            <img data-product={{item.product.id}} data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">
                    
                            <img data-product={{item.product.id}} data-action="remove" class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}">
                        </div>
                    </div>
                    <div style="flex:1"><p>৳{{item.get_total}}</p></div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock content %}

src/store/templates/store/checkout.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <div class="row">
		<div class="col-lg-6">
			<div class="box-element" id="form-wrapper">
				<form id="form">
					<div id="user-info">
						<div class="form-field">
							<input required class="form-control" type="text" name="name" placeholder="Name..">
						</div>
						<div class="form-field">
							<input required class="form-control" type="email" name="email" placeholder="Email..">
						</div>
					</div>
					
					<div id="shipping-info">
						<hr>
						<p>Shipping Information:</p>
						<hr>
						<div class="form-field">
							<input class="form-control" type="text" name="address" placeholder="Address..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="city" placeholder="City..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="state" placeholder="State..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="country" placeholder="Zip code..">
						</div>
					</div>

					<hr>
					<input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
				</form>
			</div>

			<br>
			<div class="box-element hidden" id="payment-info">
				<small>Paypal Options</small>
				<button id="make-payment">Make Payment</button>
			</div>
			
		</div>

		<div class="col-lg-6">
			<div class="box-element">
				<a  class="btn btn-outline-dark" href="{% url 'store:cart' %}">&#x2190; Back to Cart</a>
				<hr>
				<h3>Order Summary</h3>
				<hr>
				{% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{item.product.image.url}}"></div>
					<div style="flex:2"><p>{{item.product.name}}</p></div>
					<div style="flex:1"><p>${{item.product.price}}</p></div>
					<div style="flex:1"><p>x{{item.quantity}}</p></div>
				</div>
				{% endfor %}

				
				<h5>Items:   {{order.get_cart_items}}</h5>
				<h5>Total:   ${{order.get_cart_total|floatformat:2}}</h5>
				
			</div>
		</div>
	</div>

<script>
	const user = '{{ request.user }}'
	const csrftoken = '{{ csrf_token }}'
</script>

<script type="text/javascript">
	var shipping = '{{order.shipping}}'
	var total = '{{order.get_cart_total}}'

    
    if(shipping == 'False'){
    	document.getElementById('shipping-info').innerHTML = ''
    }

    //if (user != 'AnonymousUser'){
    //	document.getElementById('user-info').innerHTML = ''
    //}

    if(shipping == 'False' && user != 'AnonymousUser'){
    	//Hide entire form if user is logged in and shipping is false
    	document.getElementById('form-wrapper').classList.add("hidden");
    	//show payment if logged in user wants to buy an item that does not require 
    	//shipping
    	document.getElementById('payment-info').classList.remove('hidden');
    }

    var form = document.getElementById('form')

    form.addEventListener('submit', function(e){
    	e.preventDefault()
    	console.log('Form submitted....')
    	document.getElementById('form-button').classList.add('hidden')
    	document.getElementById('payment-info').classList.remove('hidden')


        })

    document.getElementById('make-payment').addEventListener('click', function(e){
    	submitFormData()

    })

    function submitFormData(){
    	console.log('Payment button clicked')

    	var userFormData = {
    		'name':null,
    		'email':null,
    		'total':total,
    	}

    	var shippingInfo = {
    	    'address':null,
    		'city':null,
    		'state':null,
    		'zipcode':null,

    	}

    	if(shipping != 'False'){
    		shippingInfo.address = form.address.value
    		shippingInfo.city = form.city.value
    		shippingInfo.state = form.state.value
    		shippingInfo.zipcode = form.zipcode.value
    	}

    	if(user != 'AnonymousUser'){
    		userFormData.name = form.name.value
    		userFormData.email = form.email.value
    		

    	}

    	var url = '/process_order/'

	    fetch(url, {
		    method: 'POST',
		    headers:{
			'Content-Type':'application/json',
			'X-CSRFToken':csrftoken,
		},
		body:JSON.stringify({'form': userFormData, 'shipping': shippingInfo})
		
	})

        .then((response) => response.json())

        .then((data) =>{
     	  console.log('Success:', data);
     	  alert('Transaction completed');
     	  window.location.href = "{% url 'store:store' %}"
    })
    


  }

</script>


{% endblock content %}

src/store/templates/store/main.html
{% extends 'product.html' %}

<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Noboni Shop</title>

	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

    <script type="text/javascript">
    	var user = '{{request.user}}'
    	

         function getToken(name) {
	     var cookieValue = null;

         if (document.cookie && document.cookie !== '') {
	     var cookies = document.cookie.split(';');

         for (var i = 0; i < cookies.length; i++) {
              var cookie = cookies[i].trim();
   // Does this cookie string begin with the name wewant? 
             if (cookie.substring(0, name.length + 1) === (name + '='))
             {

              cookieValue = decodeURIComponent(cookie.substring(
                     name.length + 1));

              break;
             }
         }
     }
     return cookieValue;
}
var csrftoken = getToken('csrftoken');

    </script>


</head>
<body>

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	  <a class="navbar-brand" href="{% url 'store:store' %}">NOBONI </a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item active">
	        <a class="nav-link"href="{% url 'store:store' %}"> Store <span class="sr-only">(current)</span></a>
	      </li>
	      
	    </ul>
	      <div class="form-inline my-2 my-lg-0">
	     	<a href="#"class="btn btn-warning">Login</a>
	     	
	     	<a href="{% url 'cart' %}">
	    		<img  id="cart-icon" src="{% static 'images/cart.png' %}">
	    	</a>
	    	<p id="cart-total">{{cartItems}}</p>

	    </div>
	  </div>
	</nav>

     <div class="container">
            <br>
            {% block content %}


            {% endblock content %}
         </div>

    
	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

	<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>


	

</body>
</html>

src/store/templates/store/store.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<div class="row">
	{% for product in products %}
		<div class="col-lg-4">
			<img class="thumbnail" src="{{product.image.url}}">
			<div class="box-element product">
				<h6><strong>{{product.name}}</strong></h6>
				<hr>

				<button data-product={{product.id}} data-action="add" class="btn btn-outline-secondary add-btn update-cart">Add to Cart</button>
				<a class="btn btn-outline-success" href="#">View</a>
				<h4 style="display: inline-block; float: right"><strong>৳{{product.price|floatformat:2}}</strong></h4>

			</div>
		</div>

		{% endfor %}
		
	</div>
	<script>
		const user = '{{ request.user }}'
		const csrftoken = '{{ csrf_token }}'
	</script>
   <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
{% endblock content %}