src/blog/urls.py
from django.urls import path
from blog.views import(

	create_blog_view,
	detail_blog_view,
	edit_blog_view,
	create_comment_view,
	comment_view,
	create_doctor_blog_view,
	doctor_detail_blog_view,
	doctor_edit_blog_view,

)

app_name = 'blog'

urlpatterns = [
	path('create/', create_blog_view, name="create"),
	path('createblog/', create_doctor_blog_view, name="doctorblogcreate"),
	path('<slug>/', detail_blog_view, name='detail'),
	path('<slug>/detail', doctor_detail_blog_view, name='doctorblogdetail'),
	path('<slug>/', create_comment_view, name='comment'),
	path('<slug>/', comment_view, name='comments'),
	path('<slug>/edit', edit_blog_view, name='edit'),
	path('<slug>/editblog', doctor_edit_blog_view, name='doctorblogedit'),


]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from personal.views import(
	home_screen_view,
    index_view,
    blogpost_view,
    userprofile_view,
    doctor_index_view,
    doctor_blogpost_view,
    doc_profile_view,
    covid_view,
    product_view,
       
)
from account.views import(
    registration_view,
    logout_view,
    login_view,
    doc_login_view,
    doc_reg_view,

)
urlpatterns = [
    path('',home_screen_view, name="home"),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', 'blog')),
    path('blogpost/',blogpost_view, name="blogpost"),
    path('doctor_blogpost/',doctor_blogpost_view, name="doctor_blogpost"),
    path('index/',index_view, name="index"),
    path('logout/',logout_view, name="logout"),
    path('login/',login_view, name="login"),
    path('doctor_login/',doc_login_view, name="doctor_login"),
    path('doctor_index/',doctor_index_view, name="doctor_index"),
    path('register/',registration_view, name="register"),
    path('doctor_register/',doc_reg_view, name="doctorregister"),
    path('userprofile/',userprofile_view, name="userprofile"),
    path('doctor_profile/',doc_profile_view, name="doctorprofile"),
    path('covidlist/',covid_view, name="covidlist"),
    path('product/',product_view, name="product"),
    path('', include('store.urls', 'store'))

   
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/blog/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete
from django.dispatch import receiver

def upload_location(instance, filename):
	file_path = 'blog/{author_id}/{title}-{filename}'.format(
				author_id=str(instance.author.id),title=str(instance.title), filename=filename)
	return file_path


class BlogPost(models.Model):
	title 					= models.CharField(max_length=50, null=False, blank=False)
	body 					= models.TextField(max_length=5000, null=False, blank=False)
	image		 			= models.ImageField(upload_to=upload_location, null=True, blank=True)
	date_published 			= models.DateTimeField(auto_now_add=True, verbose_name="date published")
	date_updated 			= models.DateTimeField(auto_now=True, verbose_name="date updated")
	author 					= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	slug 					= models.SlugField(blank=True, unique=True)

	def __str__(self):
		return self.title


class Comment(models.Model):
	comment		            = models.TextField(max_length=2000, null=False, blank=False)
	date_published 			= models.DateTimeField(auto_now_add=True, verbose_name="date published")
	author 					= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


	def __str__(self):
		return self.comment		

@receiver(post_delete, sender=BlogPost)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False) 

def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = slugify(instance.author.username + "-" + instance.title)

pre_save.connect(pre_save_blog_post_receiver, sender=BlogPost)

src/blog/forms.py
from django import forms

from blog.models import BlogPost, Comment

class CreateBlogPostForm(forms.ModelForm):

	class Meta:
		model = BlogPost
		fields = ['title', 'body', 'image']


class UpdateBlogPostForm(forms.ModelForm):

	class Meta:
		model = BlogPost
		fields = ['title', 'body', 'image']

	def save(self, commit=True):
		blog_post = self.instance
		blog_post.title = self.cleaned_data['title']
		blog_post.body = self.cleaned_data['body']

		if self.cleaned_data['image']:
			blog_post.image = self.cleaned_data['image']

		if commit:
			blog_post.save()
		return blog_post			


class CreateCommentForm(forms.ModelForm):

	class Meta:
		model = Comment
		fields = ['comment']
	

src/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from blog.models import BlogPost, Comment
from blog.forms import CreateBlogPostForm, UpdateBlogPostForm
from account.models import Account

def create_blog_view(request):

	context = {}

	user = request.user

	if request.POST:
		form = CreateBlogPostForm(request.POST or None, request.FILES or None)
		if form.is_valid():
			obj = form.save(commit=False)
			author = Account.objects.filter(username=user.username).first()
			obj.author = author
			obj.save()
			return redirect('blogpost')
		else:
			context['form'] = form	

	else:			
		form = CreateBlogPostForm()
		context['form'] = form
	return render(request, "blog/create_blog.html", context)


def detail_blog_view(request, slug):

	context = {}

	blog_post = get_object_or_404(BlogPost, slug=slug)
	context['blog_post'] = blog_post

	return render(request, 'blog/detail_blog.html', context)	

def edit_blog_view(request, slug):

	context = {}

	user = request.user
	
	blog_post = get_object_or_404(BlogPost, slug=slug)
	
	if request.POST:
		form = UpdateBlogPostForm(request.POST or None, request.FILES or None, instance=blog_post)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save()
			context['success_message'] = "Updated"
			blog_post = obj
			return redirect('blogpost')
		else:
			context['form'] = form	

	else:		
		form = UpdateBlogPostForm(
			initial = {
					"title": blog_post.title,
					"body": blog_post.body,
					"image": blog_post.image,
			}
		)
		context['form'] = form
		return render(request, 'blog/edit_blog.html', context)


def create_comment_view(request):

	context = {}

	user = request.user

	if request.POST:
		form = CreateCommentForm(request.POST or None)
		if form.is_valid():
			obj = form.save(commit=False)
			author = Account.objects.filter(username=user.username).first()
			obj.author = author
			obj.save()
			return redirect('comments')
		else:
			context['form'] = form	

	else:			
		form = CreateCommentForm()
		context['form'] = form
	return render(request, "blog/detail_blog.html", context)		


def comment_view(request):
	
	comment_post = get_object_or_404(Comment, slug=slug)
	context['comment_post'] = comment_post

	return render(request, 'blog/detail_blog.html', context)

 
def get_blog_queryset(query=None):
	queryset = []
	queries = query.split(" ") # python install 2019 = [python, install, 2019]
	for q in queries:
		posts = BlogPost.objects.filter(
				Q(title__icontains=q) | 
				Q(body__icontains=q)
			).distinct()

		for post in posts:
			queryset.append(post)

	return list(set(queryset))


def create_doctor_blog_view(request):

	context = {}

	user = request.user

	if request.POST:
		form = CreateBlogPostForm(request.POST or None, request.FILES or None)
		if form.is_valid():
			obj = form.save(commit=False)
			author = Account.objects.filter(username=user.username).first()
			obj.author = author
			obj.save()
			return redirect('doctor_blogpost')
		else:
			context['form'] = form	

	else:			
		form = CreateBlogPostForm()
		context['form'] = form
	return render(request, "blog/doctor_create_blog.html", context)	


def doctor_detail_blog_view(request, slug):

	context = {}

	blog_post = get_object_or_404(BlogPost, slug=slug)
	context['blog_post'] = blog_post

	return render(request, 'blog/doctor_detail_blog.html', context)	


def doctor_edit_blog_view(request, slug):

	context = {}

	user = request.user
	
	blog_post = get_object_or_404(BlogPost, slug=slug)
	
	if request.POST:
		form = UpdateBlogPostForm(request.POST or None, request.FILES or None, instance=blog_post)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save()
			context['success_message'] = "Updated"
			blog_post = obj
			return redirect('doctor_blogpost')
		else:
			context['form'] = form	

	else:		
		form = UpdateBlogPostForm(
			initial = {
					"title": blog_post.title,
					"body": blog_post.body,
					"image": blog_post.image,
			}
		)
		context['form'] = form
		return render(request, 'blog/doctor_edit_blog.html', context)	

src/blog/templates/blog/create_blog.html
{% extends 'blogpost.html' %}


{% block content %}

<style>
  .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}
</style>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    
<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">
			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group">
					<label for="id_title">Title</label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group">
					<label for="id_body">Content</label>
					<textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="This blog is about..." required></textarea>
				</div>

				<!-- Image -->
				<div class="form-group">
					<label for="id_image">Image</label>
					<input  type="file" name="image" id="id_image" accept="image/*" required>
				</div>

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">POST</button>
			</form>	
		</div>
	</div>
</div>

{% endblock content %}

src/blog/templates/blog/detail_blog.html
{% extends 'blogpost.html' %}


{% block content %}

<style>
	.card{
		max-width: 700px;
	}
	.card-body{
		padding: 20px;
	}
</style>
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
<div class="container">
	<div class="row">

		<!-- Blog Post -->
		<div class="card m-auto">
			<img class="card-img-top" src="{{blog_post.image.url}}">
			<div class="card-body mt-2 mb-2">
			  <h2 class="card-title">{{blog_post.title}}</h2>
			  <p class="card-text">{{blog_post.body}}</p>
			  <div class="container">
				<div class="row">
				<div class="col-lg-7 offset-lg-1">
					<label for="id_body">Comments</label>
					<div class="card-body mt-2 mb-2">
					  <p class="card-text">{{comment_post.comment}}</p>
					<div class="card-footer text-muted">
			      Posted on {{comment_post.date_published}} by {{comment_post.author}}
			      </div>
			      <form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}
					<div class="form-group">	
					<textarea class="form-control" rows="5" type="text" name="body" id="id_body" placeholder="Write your Comments" required></textarea>
				</div>
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">POST</button>
			    </form>
			</div>
		</div>
	</div>

			  {% if blog_post.author == request.user %}
			  	<a href="{% url 'blog:edit' blog_post.slug %}" class="btn btn-primary">Update</a>
			  {% endif %}
			</div>
			<div class="card-footer text-muted">
			  Updated on {{blog_post.date_updated}} by {{blog_post.author}}
			</div>
		</div>
	</div>
</div>

{% endblock content %}

src/blog/templates/blog/doctor_create_blog.html
{% extends 'doctor_blogpost.html' %}


{% block content %}

<style>
  .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}
</style>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    
<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">
			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group">
					<label for="id_title">Title</label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group">
					<label for="id_body">Content</label>
					<textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="This blog is about..." required></textarea>
				</div>

				<!-- Image -->
				<div class="form-group">
					<label for="id_image">Image</label>
					<input  type="file" name="image" id="id_image" accept="image/*" required>
				</div>

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">POST</button>
			</form>	
		</div>
	</div>
</div>

{% endblock content %}

src/blog/templates/blog/doctor_detail_blog.html
{% extends 'doctor_blogpost.html' %}


{% block content %}

<style>
	.card{
		max-width: 700px;
	}
	.card-body{
		padding: 20px;
	}
</style>
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
<div class="container">
	<div class="row">

		<!-- Blog Post -->
		<div class="card m-auto">
			<img class="card-img-top" src="{{blog_post.image.url}}">
			<div class="card-body mt-2 mb-2">
			  <h2 class="card-title">{{blog_post.title}}</h2>
			  <p class="card-text">{{blog_post.body}}</p>
			  <div class="container">
				<div class="row">
				<div class="col-lg-7 offset-lg-1">
					<label for="id_body">Comments</label>
					<div class="card-body mt-2 mb-2">
					  <p class="card-text">{{comment_post.comment}}</p>
					<div class="card-footer text-muted">
			      Posted on {{comment_post.date_published}} by {{comment_post.author}}
			      </div>
			      <form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}
					<div class="form-group">	
					<textarea class="form-control" rows="5" type="text" name="body" id="id_body" placeholder="Write your Comments" required></textarea>
				</div>
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">POST</button>
			    </form>
			</div>
		</div>
	</div>

			  {% if blog_post.author == request.user %}
			  	<a href="{% url 'blog:doctorblogedit' blog_post.slug %}" class="btn btn-primary">Update</a>
			  {% endif %}
			</div>
			<div class="card-footer text-muted">
			  Updated on {{blog_post.date_updated}} by {{blog_post.author}}
			</div>
		</div>
	</div>
</div>

{% endblock content %}

src/blog/templates/blog/doctor_edit_blog.html
{% extends 'doctor_blogpost.html' %}


{% block content %}

<style>
   .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}

	.image {
	  opacity: 1;
	  transition: .5s ease;
	  backface-visibility: hidden;
	}

	.middle {
	  transition: .5s ease;
	  opacity: 0;
	  position: absolute;
	  text-align: center;
	  top: 50%;
	  left: 50%;
	  transform: translate(-50%, -50%);
	
	}
	.image-group{
		position: relative;
  		text-align: center;
  		cursor:pointer;
	}

	.image-group:hover .image {
	  opacity: 0.3;
	}

	.image-group:hover .middle {
	  opacity: 1;
	}

	.text {
	  margin: auto;
	  background-color: #4CAF50;
	  color: white;
	  font-size: 15px;
	  padding: 15px;
	}
</style>
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    
<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}

			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group">
					<label for="id_title">Title</label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" value="{{form.initial.title}}" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group">
					<label for="id_body">Content</label>
					<textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="This blog is about..." 
					required>{{form.initial.body}}</textarea>
				</div>

				<!-- Image -->
				<div class="form-group image-group" id="id_image_group">
					<img class="img-fluid image" src="{{form.initial.image.url}}" id="id_image_display">
					  <div class="middle">
					    <div class="text">Change image</div>
					  </div>
				</div>
				<input type="file" name="image" id="id_image_file" accept="image/*" onchange="readURL(this)">
				

				{% for field in form %}
					<p>
						{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
						{% endfor %}
					</p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
						<p>{{form.non_field_errors}}</p>
					</div>
				{% endif %}

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Update</button>
			</form>	
		</div>
	</div>
</div>

<script type="text/javascript">
	document.getElementById('id_image_group').onclick = function(event){
    	document.getElementById('id_image_file').click();
    };

	function readURL(input){
		var reader = new FileReader();
		reader.onload = function (e) {
            $('#id_image_display')
                .attr('src', e.target.result)
        };
		reader.readAsDataURL(input.files[0]);
	}
</script>

{% endblock content %}

src/blog/templates/blog/edit_blog.html
{% extends 'blogpost.html' %}


{% block content %}

<style>
   .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}

	.image {
	  opacity: 1;
	  transition: .5s ease;
	  backface-visibility: hidden;
	}

	.middle {
	  transition: .5s ease;
	  opacity: 0;
	  position: absolute;
	  text-align: center;
	  top: 50%;
	  left: 50%;
	  transform: translate(-50%, -50%);
	
	}
	.image-group{
		position: relative;
  		text-align: center;
  		cursor:pointer;
	}

	.image-group:hover .image {
	  opacity: 0.3;
	}

	.image-group:hover .middle {
	  opacity: 1;
	}

	.text {
	  margin: auto;
	  background-color: #4CAF50;
	  color: white;
	  font-size: 15px;
	  padding: 15px;
	}
</style>
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    
<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}

			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group">
					<label for="id_title">Title</label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" value="{{form.initial.title}}" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group">
					<label for="id_body">Content</label>
					<textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="This blog is about..." 
					required>{{form.initial.body}}</textarea>
				</div>

				<!-- Image -->
				<div class="form-group image-group" id="id_image_group">
					<img class="img-fluid image" src="{{form.initial.image.url}}" id="id_image_display">
					  <div class="middle">
					    <div class="text">Change image</div>
					  </div>
				</div>
				<input type="file" name="image" id="id_image_file" accept="image/*" onchange="readURL(this)">
				

				{% for field in form %}
					<p>
						{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
						{% endfor %}
					</p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
						<p>{{form.non_field_errors}}</p>
					</div>
				{% endif %}

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Update</button>
			</form>	
		</div>
	</div>
</div>

<script type="text/javascript">
	document.getElementById('id_image_group').onclick = function(event){
    	document.getElementById('id_image_file').click();
    };

	function readURL(input){
		var reader = new FileReader();
		reader.onload = function (e) {
            $('#id_image_display')
                .attr('src', e.target.result)
        };
		reader.readAsDataURL(input.files[0]);
	}
</script>

{% endblock content %}